### ISSUE TITLE
Feature request: extension of keyword

### ISSUE THREAD

**Issue by Raccooneer** [zerefdev/todo-highlighter#3]
Hey,

love the extension!

I had the feature idea / feature request to extend the Keywords by `FIXME:` and `NOTE:`. In possibly different colours. I have not even the slightest idea where to start, but I'd like to support of course.

Best

**Comment by benc-uk** [comment]
Came here to ask exactly the same

This is best extension I've found for managing TODOs in code, there's more complex ones like todo tree, but this is a great as it does just enough without being complex

I'd like to add the option to pickup other keywords as well

**Comment by zerefdev** [comment]
@benc-uk @Racooneer 
Since this extension is dedicated to TODOs and only that, I created something that solves this problem, see `extra` branch [here](https://github.com/zerefdev/todo-highlighter/tree/extra)  
You can either compile it using `vsce` or download the compiled version [here](https://github.com/zerefdev/todo-highlighter/releases/tag/v0.0.1) and install it directly in vscode: **Extensions -> ... -> install from VSIX...** Don't forget to disable the existing one.

see [README.md](https://github.com/zerefdev/todo-highlighter/tree/extra#readme) for information and example.

**Comment by benc-uk** [comment]
This is great thanks!

**Comment by Raccooneer** [comment]
Works perfectly
